#!/bin/sh

export INSTALL_PATH=/usr/lib/mmc
export ARCH=`uname -m`
export LD_LIBRARY_PATH="${INSTALL_PATH}/collating/fragment:${INSTALL_PATH}/collating/magic/lib/magic/linux-${ARCH}"

(cd ${INSTALL_PATH} && env python ${INSTALL_PATH}/mmc.py $*)
