#!/bin/sh

INSTALL_PATH=/usr/lib/mmc

PYTHONPATH="${INSTALL_PATH}/collating/fragment:${INSTALL_PATH}" LD_LIBRARY_PATH="${INSTALL_PATH}/collating/fragment" env python ${INSTALL_PATH}/gui/gui_fc.py $*

