# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_carving_ui.ui'
#
# Created: Thu Aug  4 16:01:48 2011
#      by: pyside-uic 0.2.11 running on PySide 1.0.5
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_filecarvingWidget(object):
    def setupUi(self, filecarvingWidget):
        filecarvingWidget.setObjectName("filecarvingWidget")
        filecarvingWidget.resize(626, 578)
        filecarvingWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.verticalLayout = QtGui.QVBoxLayout(filecarvingWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.srcdstLayout = QtGui.QGridLayout()
        self.srcdstLayout.setObjectName("srcdstLayout")
        self.inputFile = QtGui.QLineEdit(filecarvingWidget)
        self.inputFile.setText("")
        self.inputFile.setObjectName("inputFile")
        self.srcdstLayout.addWidget(self.inputFile, 0, 0, 1, 1)
        self.inputFileButton = QtGui.QPushButton(filecarvingWidget)
        self.inputFileButton.setObjectName("inputFileButton")
        self.srcdstLayout.addWidget(self.inputFileButton, 0, 1, 1, 1)
        self.outputDirButton = QtGui.QPushButton(filecarvingWidget)
        self.outputDirButton.setObjectName("outputDirButton")
        self.srcdstLayout.addWidget(self.outputDirButton, 2, 1, 1, 1)
        self.outputDir = QtGui.QLineEdit(filecarvingWidget)
        self.outputDir.setText("")
        self.outputDir.setObjectName("outputDir")
        self.srcdstLayout.addWidget(self.outputDir, 2, 0, 1, 1)
        self.fsInfo = QtGui.QLabel(filecarvingWidget)
        self.fsInfo.setObjectName("fsInfo")
        self.srcdstLayout.addWidget(self.fsInfo, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.srcdstLayout)
        self.preprocessingLayout = QtGui.QHBoxLayout()
        self.preprocessingLayout.setObjectName("preprocessingLayout")
        self.label_5 = QtGui.QLabel(filecarvingWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.preprocessingLayout.addWidget(self.label_5)
        self.preprocessing = QtGui.QComboBox(filecarvingWidget)
        self.preprocessing.setObjectName("preprocessing")
        self.preprocessingLayout.addWidget(self.preprocessing)
        self.verticalLayout.addLayout(self.preprocessingLayout)
        self.groupBox_3 = QtGui.QGroupBox(filecarvingWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.fsLayout = QtGui.QGridLayout(self.groupBox_3)
        self.fsLayout.setObjectName("fsLayout")
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.fsLayout.addWidget(self.label, 0, 0, 1, 1)
        self.fragmentSize = QtGui.QLineEdit(self.groupBox_3)
        self.fragmentSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fragmentSize.setObjectName("fragmentSize")
        self.fsLayout.addWidget(self.fragmentSize, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.fsLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.offset = QtGui.QLineEdit(self.groupBox_3)
        self.offset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.offset.setObjectName("offset")
        self.fsLayout.addWidget(self.offset, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(filecarvingWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.fragmentizerLayout = QtGui.QGridLayout(self.groupBox_2)
        self.fragmentizerLayout.setObjectName("fragmentizerLayout")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.fragmentizerLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.blockGap = QtGui.QLineEdit(self.groupBox_2)
        self.blockGap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blockGap.setObjectName("blockGap")
        self.fragmentizerLayout.addWidget(self.blockGap, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.fragmentizerLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.minimumFragmentSize = QtGui.QLineEdit(self.groupBox_2)
        self.minimumFragmentSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minimumFragmentSize.setObjectName("minimumFragmentSize")
        self.fragmentizerLayout.addWidget(self.minimumFragmentSize, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(filecarvingWidget)
        self.groupBox.setObjectName("groupBox")
        self.videoparamLayout = QtGui.QGridLayout(self.groupBox)
        self.videoparamLayout.setObjectName("videoparamLayout")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.videoparamLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.headerSize = QtGui.QLineEdit(self.groupBox)
        self.headerSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.headerSize.setObjectName("headerSize")
        self.videoparamLayout.addWidget(self.headerSize, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.videoparamLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.extractSize = QtGui.QLineEdit(self.groupBox)
        self.extractSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extractSize.setObjectName("extractSize")
        self.videoparamLayout.addWidget(self.extractSize, 1, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.videoparamLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.assemblyMethod = QtGui.QComboBox(self.groupBox)
        self.assemblyMethod.setObjectName("assemblyMethod")
        self.videoparamLayout.addWidget(self.assemblyMethod, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.resultTable = QtGui.QTableWidget(filecarvingWidget)
        self.resultTable.setObjectName("resultTable")
        self.resultTable.setColumnCount(0)
        self.resultTable.setRowCount(0)
        self.verticalLayout.addWidget(self.resultTable)
        self.progressBar = QtGui.QProgressBar(filecarvingWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.outformatLayout = QtGui.QHBoxLayout()
        self.outformatLayout.setObjectName("outformatLayout")
        self.label_7 = QtGui.QLabel(filecarvingWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.outformatLayout.addWidget(self.label_7)
        self.outputformat = QtGui.QComboBox(filecarvingWidget)
        self.outputformat.setObjectName("outputformat")
        self.outformatLayout.addWidget(self.outputformat)
        self.verticalLayout.addLayout(self.outformatLayout)
        self.actionLayout = QtGui.QHBoxLayout()
        self.actionLayout.setObjectName("actionLayout")
        self.classifyButton = QtGui.QPushButton(filecarvingWidget)
        self.classifyButton.setObjectName("classifyButton")
        self.actionLayout.addWidget(self.classifyButton)
        self.reassembleButton = QtGui.QPushButton(filecarvingWidget)
        self.reassembleButton.setEnabled(False)
        self.reassembleButton.setObjectName("reassembleButton")
        self.actionLayout.addWidget(self.reassembleButton)
        self.processButton = QtGui.QPushButton(filecarvingWidget)
        self.processButton.setObjectName("processButton")
        self.actionLayout.addWidget(self.processButton)
        self.verticalLayout.addLayout(self.actionLayout)

        self.retranslateUi(filecarvingWidget)
        QtCore.QMetaObject.connectSlotsByName(filecarvingWidget)

    def retranslateUi(self, filecarvingWidget):
        filecarvingWidget.setWindowTitle(QtGui.QApplication.translate("filecarvingWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.inputFileButton.setText(QtGui.QApplication.translate("filecarvingWidget", "&Data Source", None, QtGui.QApplication.UnicodeUTF8))
        self.outputDirButton.setText(QtGui.QApplication.translate("filecarvingWidget", "&Export Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.fsInfo.setText(QtGui.QApplication.translate("filecarvingWidget", "FS Info: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("filecarvingWidget", "Preprocessing: ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("filecarvingWidget", "File System Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("filecarvingWidget", "Block Size", None, QtGui.QApplication.UnicodeUTF8))
        self.fragmentSize.setText(QtGui.QApplication.translate("filecarvingWidget", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("filecarvingWidget", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.offset.setText(QtGui.QApplication.translate("filecarvingWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("filecarvingWidget", "Fragmentizer Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("filecarvingWidget", "Block Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.blockGap.setText(QtGui.QApplication.translate("filecarvingWidget", "16384", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("filecarvingWidget", "Minimum Fragment Size", None, QtGui.QApplication.UnicodeUTF8))
        self.minimumFragmentSize.setStatusTip(QtGui.QApplication.translate("filecarvingWidget", "Minimum fragment size in blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.minimumFragmentSize.setText(QtGui.QApplication.translate("filecarvingWidget", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("filecarvingWidget", "Video Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("filecarvingWidget", "Header Size (bytes)", None, QtGui.QApplication.UnicodeUTF8))
        self.headerSize.setStatusTip(QtGui.QApplication.translate("filecarvingWidget", "Size of the header in bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.headerSize.setText(QtGui.QApplication.translate("filecarvingWidget", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("filecarvingWidget", "Extract Size (kB)", None, QtGui.QApplication.UnicodeUTF8))
        self.extractSize.setStatusTip(QtGui.QApplication.translate("filecarvingWidget", "Size of the subfragment to forward to the decoder", None, QtGui.QApplication.UnicodeUTF8))
        self.extractSize.setText(QtGui.QApplication.translate("filecarvingWidget", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("filecarvingWidget", "Assembly Method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("filecarvingWidget", "Output Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.classifyButton.setText(QtGui.QApplication.translate("filecarvingWidget", "&Classify", None, QtGui.QApplication.UnicodeUTF8))
        self.reassembleButton.setText(QtGui.QApplication.translate("filecarvingWidget", "&Reassemble", None, QtGui.QApplication.UnicodeUTF8))
        self.processButton.setText(QtGui.QApplication.translate("filecarvingWidget", "&Process (do it all)", None, QtGui.QApplication.UnicodeUTF8))

